services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=myblog_backend.settings
    restart: unless-stopped

  postgres:
    image: postgres:18
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    ports:
      - "127.0.0.1:8080:80"

    depends_on:
      - postgres

volumes:
  postgres_data:
