# Generated by Django 5.2.16 on 2026-07-26 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderations', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddIndex(
            model_name='moderation',
            index=models.Index(fields=['status', '-created_at'], name='moderations_status_6c4346_idx'),
        ),
        migrations.AddIndex(
            model_name='moderation',
            index=models.Index(fields=['content_type', 'object_id'], name='moderations_content_0bc754_idx'),
        ),
    ]
