# Generated by Django 5.2.16 on 2026-08-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_backfill_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
